version: '3.7'

services:
  db:
    image: igrich/flaskblog_db:v1.1
    build:
      context: ./db
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - igrich_network
    ports:
      - "5431:5431"
    expose:
      - 5431
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog

  flaskblog:
    image: igrich/flaskblog:v1.1
    build:
      context: .
      dockerfile: ./Dockerfile
    #command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5001"]
    ports:
      - 5001:5001
    networks:
      - igrich_network
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    links: 
      - db:blog
    depends_on:
      - db

networks:
  igrich_network: