version: '3.4'

services:
  flaskblog:
    image: flaskblog
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    networks:
      - backend
      environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    networks:
      - backend  
      expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blogs
    # volumes:
    #   - "db-data:/var/lib/postgresql/data"      
  
networks:
  frontend:
  backend: