version: '3.7'

services:
  flaskblog:
    image: flaskblog
    build:
      context: .
      dockerfile: ./Dockerfile
      command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5001"]
      ports:
        - 5001:5001
        - 5678:5678
    networks:
      - backend
    environment:
      - FLASK_ENV=development
    links: 
      - db:db
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    networks:
      - backend  
    expose:
    - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blogs
      - POSTGRES_HOST_AUTH_METHOD=trust
      # volumes:
    #   - "db-data:/var/lib/postgresql/data"      

networks:
  frontend:
  backend: