version: '3.4'

services:
  flaskblog:
    image: flaskblog
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001

  postgres:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres