version: '3.4'

services:
  flaskblog:
    image: flaskblog
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blogs
    volumes:
      - "db-data:/var/lib/postgresql/data"      
  